# 01 Data setup
Downloads 5-minute OHLCV data from Binance public REST API. No API key required.

In [1]:
from pathlib import Path
import sys
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
if str(PROJECT_ROOT) not in sys.path: sys.path.append(str(PROJECT_ROOT))
print('Project root:', PROJECT_ROOT)
from src.config import SYMBOLS,INTERVAL,START_DATE,END_DATE,RAW_DIR
from src.binance_data import download_symbol,load_raw_files
print(SYMBOLS, INTERVAL, START_DATE, END_DATE)

Project root: c:\Users\vidhi\Downloads\pro_crypto_trading_system\pro_crypto_trading_system
['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT'] 5m 2021-01-01 2026-01-01

In [2]:
downloaded=[]
for symbol in SYMBOLS:
    df=download_symbol(symbol,INTERVAL,START_DATE,END_DATE)
    if not df.empty: downloaded.append(df)
print(f'Downloaded {len(downloaded)} / {len(SYMBOLS)} symbols')

Downloading BTCUSDT...
Request failed: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/klines?symbol=BTCUSDT&interval=5m&startTime=1693522800001&endTime=1767225600000&limit=1000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000206DDECEC10>, 'Connection to api.binance.com timed out. (connect timeout=60)')). Retrying in 1s...
Saved BTCUSDT: (525676, 11) -> C:\Users\vidhi\Downloads\pro_crypto_trading_system\pro_crypto_trading_system\data\raw\BTCUSDT_5m_2021-01-01_2026-01-01.parquet
Downloading ETHUSDT...
Saved ETHUSDT: (525676, 11) -> C:\Users\vidhi\Downloads\pro_crypto_trading_system\pro_crypto_trading_system\data\raw\ETHUSDT_5m_2021-01-01_2026-01-01.parquet
Downloading BNBUSDT...
Request failed: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/klines?symbol=BNBUSDT&interval=5m&startTime=1619077800001&endTime=1767225600000&limit=1000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000206DDFA0910>, 'Connection to api.binance.com timed out. (connect timeout=60)')). Retrying in 1s...
Request failed: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/klines?symbol=BNBUSDT&interval=5m&startTime=1737022800001&endTime=1767225600000&limit=1000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000206DDFA0CD0>, 'Connection to api.binance.com timed out. (connect timeout=60)')). Retrying in 1s...
Saved BNBUSDT: (525676, 11) -> C:\Users\vidhi\Downloads\pro_crypto_trading_system\pro_crypto_trading_system\data\raw\BNBUSDT_5m_2021-01-01_2026-01-01.parquet
Downloading SOLUSDT...
Saved SOLUSDT: (525676, 11) -> C:\Users\vidhi\Downloads\pro_crypto_trading_system\pro_crypto_trading_system\data\raw\SOLUSDT_5m_2021-01-01_2026-01-01.parquet
Downloading XRPUSDT...
Request failed: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). Retrying in 1s...
Saved XRPUSDT: (525676, 11) -> C:\Users\vidhi\Downloads\pro_crypto_trading_system\pro_crypto_trading_system\data\raw\XRPUSDT_5m_2021-01-01_2026-01-01.parquet
Downloaded 5 / 5 symbols

In [3]:
raw=load_raw_files()
print(raw.shape)
print(raw.columns.tolist())
raw.head()

(2628380, 11)
['Datetime', 'symbol', 'Open', 'High', 'Low', 'Close', 'Volume', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_volume', 'taker_buy_quote_volume']

,Datetime,symbol,Open,High,Low,Close,Volume,quote_asset_volume,number_of_trades,taker_buy_base_volume,taker_buy_quote_volume
0,2021-01-01 00:00:00+00:00,BNBUSDT,37.3596,37.4221,37.2502,37.2639,5695.351,212739.076283,799,2928.143,109395.212384
1,2021-01-01 00:05:00+00:00,BNBUSDT,37.2596,37.2850,37.0743,37.1082,21319.204,791937.021860,1762,12079.071,448623.001496
2,2021-01-01 00:10:00+00:00,BNBUSDT,37.1082,37.1546,36.9706,37.0022,8278.101,306915.404129,1319,3180.308,117931.377995
3,2021-01-01 00:15:00+00:00,BNBUSDT,37.0134,37.1332,36.9636,37.1200,5000.406,185188.792115,940,2133.491,79042.101395
4,2021-01-01 00:20:00+00:00,BNBUSDT,37.1186,37.1302,37.0341,37.0935,6107.471,226489.159293,686,3158.859,117137.329999

In [4]:
raw.groupby('symbol').agg(rows=('Close','size'), start=('Datetime','min'), end=('Datetime','max'))

           rows                     start                       end
symbol
BNBUSDT  525676 2021-01-01 00:00:00+00:00 2026-01-01 00:00:00+00:00
BTCUSDT  525676 2021-01-01 00:00:00+00:00 2026-01-01 00:00:00+00:00
ETHUSDT  525676 2021-01-01 00:00:00+00:00 2026-01-01 00:00:00+00:00
SOLUSDT  525676 2021-01-01 00:00:00+00:00 2026-01-01 00:00:00+00:00
XRPUSDT  525676 2021-01-01 00:00:00+00:00 2026-01-01 00:00:00+00:00